name: Build contracts and release 
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Unique release name'
        required: true
        type: string
permissions:
  contents: write
  pull-requests: write 
  repository-projects: write
  packages: write
defaults:
  run:
    working-directory: ./

jobs:
  release-soroswap-aggregator:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}                        # use git tag as unique release name
      release_description: 'Soroswap Aggregator contract release' # some boring placeholder text to attach
      relative_path: '["contracts/"]'                   # relative path to your really awesome contract
      package: '["soroswap-aggregator", "soroswap-aggregator-deployer", "soroswap-adapter", "phoenix-adapter", "adapter-interface"]'                              # package name to build
      make_target: 'contracts/Makefile'                # make target to invoke
    secrets:  # the authentication token will be automatically created by GitHub
      release_token: ${{ secrets.GITHUB_TOKEN }}                # don't modify this line
